sudo: required
services:
  - docker
  
before_install:
  - docker build -t elsaveraamores/docker-react -f Dockerfile.dev .

script:
  - docker run elsaveraamores/docker-react npm run test -- --coverage
